### ISSUE TITLE
zfmm2d

### ISSUE THREAD

**Issue by mattearnshaw** [ludvigak/FMMLIB2D.jl#1]
is there any plan to implement interface to the `zfmm2d*` routines? thanks

**Comment by ludvigak** [comment]
Hi! Until now I wasn't sure if there was any interest. Now that you asked for it, I've added it to a new release (v0.3.0). It should make its way into the package management system within a day or two.

**Comment by mattearnshaw** [comment]
@ludvigak thanks!
